version: "1.0"
mode: parallel

stages:
  - setup
  - ZD_9336_test1
  - ZD_9336_test2
  - cleanup

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lrochette/ptm-tests"
    revision: "main"
    stage: setup

  create_project:
    title: "creating the test project"
    image: codefresh/cli
    stage: setup
    fail_fast: false
    commands:
      - export CF_API_KEY=${{MY_API_KEY}}
      - codefresh create project ptm -t test -t ptm

  GettingPluginVersion:
    title: Getting Plugin Version
    image: codefresh/cli
    stage: setup
    working_directory: "${{clone}}/step"
    commands:
      - cf_export PLUGIN_VERSION=$(yq -r .metadata.version ./step.yaml)
    when:
      steps:
        all:
          - name: clone
            'on':
              - success
  ZD_9336_test1:
    type: laurent-cf/pipeline-trigger-merge:1.1.1
    title: "ZD_9336_test1 - on is quoted"
    working_directory: ${{clone}}/ZD-9336/test1
    stage: ZD_9336_test1
    arguments:
      SPEC: spec.yaml
      TRIGGERS: trig.yaml
      CF_API_KEY: ${{MY_API_KEY}}
    when:
      steps:
        all:
          - name: clone
            'on':
              - success
          - name: create_project
            on:
              - finished
  ZD_9336_test2:
    type: laurent-cf/pipeline-trigger-merge:1.1.1
    title: "ZD_9336_test2 - on is unquoted"
    working_directory: ${{clone}}/ZD-9336/test2
    stage: ZD_9336_test2
    arguments:
      SPEC: spec.yaml
      TRIGGERS: trig.yaml
      CF_API_KEY: ${{MY_API_KEY}}
    when:
      steps:
        all:
          - name: clone
            'on':
              - success
          - name: create_project
            on:
              - finished
  run-ZD9336-test1:
    title: Running the pipeline created
    type: codefresh-run
    stage: ZD_9336_test1
    arguments:
      PIPELINE_ID: ptm/ZD9336-test1
      TRIGGER_ID: trig1
      BRANCH: main
    when:
      steps:
        - name: ZD_9336_test1
          on:
            - success
  run-ZD9336-test2:
    title: Running the pipeline created
    type: codefresh-run
    stage: ZD_9336_test2
    arguments:
      PIPELINE_ID: ptm/ZD9336-test2
      TRIGGER_ID: trig1
      BRANCH: main
    when:
      steps:
        - name: ZD_9336_test2
          on:
            - success

  delete-ZD9336-pipelines:
    title: deleting the pipeline created
    image: codefresh/cli
    stage: cleanup
    commands:
      - export CF_API_KEY=${{MY_API_KEY}}
      - codefresh delete pip ptm/ZD9336-test1
      - codefresh delete pip ptm/ZD9336-test2
    when:
      steps:
        all:
          - name: run-ZD9336-test1
            on:
              - finished
          - name: run-ZD9336-test2
            on:
              - finished
  cleanup:
    title: Deleting the test project
    image: codefresh/cli
    stage: cleanup
    commands:
      - export CF_API_KEY=${{MY_API_KEY}}
      - codefresh delete project ptm
    when:
      steps:
        - name: delete-ZD9336-pipelines
          on:
            - success
