version: "1.0"

stages:
  - setup
  - test1
  - cleanup

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lrochette/ptm-tests"
    revision: "main"
    stage: setup

  create_project:
    title: "creating the test project"
    image: codefresh/cli
    stage: setup
    commands:
      - codefresh create project ptm -t test -t ptm

  create_pipeline:
    type: pipeline-trigger-merge
    title: "ZD-9936"
    working_directory: ${{clone}}/ZD-9336
    stage: test1
    arguments:
      SPEC: spec.yaml
      TRIGGERS: trig.yaml

  cleanup:
    title: creating the test project
    image: codefresh/cli
    stage: cleanup
    commands:
      - codefresh delete project ptm
